### ISSUE TITLE
💡 Feature: CI/CD 환경 구축

### ISSUE THREAD

**Issue by ghkdgus29** [mujik-tigers/course-registration-system#2]
## Key Feature

AWS를 사용하여 자동 배포 환경을 구성합니다.
Nginx를 통해 HTTPS 프로토콜을 사용합니다. 

### Feature List

- [x] AWS를 사용하여 자동 배포 환경을 구성
- [x] Nginx에 HTTPS 인증서 설정

**Comment by yeonise** [comment]
https://course-registration-system.site/
